version: 2
jobs:
  build:
    working_directory: ~/app/AngularCircleCITest/ClientApp 
    docker:
      - image: circleci/node:8-browsers
    steps:
      - checkout
      - run: npm install
      - save_cache:
          key: AngularCircleCITest-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - "node_modules"
      
